BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "industry_codes" (
	"ma_nganh"	TEXT,
	"ten_nganh"	TEXT NOT NULL,
	PRIMARY KEY("ma_nganh")
);
INSERT INTO "industry_codes" VALUES ('0111','Trồng lúa');
INSERT INTO "industry_codes" VALUES ('0112','Trồng ngô và cây lương thực có hạt khác');
INSERT INTO "industry_codes" VALUES ('0113','Trồng cây lấy củ có chất bột');
INSERT INTO "industry_codes" VALUES ('0114','Trồng cây mía');
INSERT INTO "industry_codes" VALUES ('0115','Trồng cây thuốc lá, thuốc lào');
INSERT INTO "industry_codes" VALUES ('0116','Trồng cây lấy sợi');
INSERT INTO "industry_codes" VALUES ('0117','Trồng cây có hạt chứa dầu');
INSERT INTO "industry_codes" VALUES ('0118','Trồng rau, đậu các loại và trồng hoa');
INSERT INTO "industry_codes" VALUES ('0119','Trồng cây hàng năm khác');
INSERT INTO "industry_codes" VALUES ('0121','Trồng cây ăn quả');
INSERT INTO "industry_codes" VALUES ('0122','Trồng cây lấy quả chứa dầu');
INSERT INTO "industry_codes" VALUES ('0123','Trồng cây điều');
INSERT INTO "industry_codes" VALUES ('0124','Trồng cây hồ tiêu');
INSERT INTO "industry_codes" VALUES ('0125','Trồng cây cao su');
INSERT INTO "industry_codes" VALUES ('0126','Trồng cây cà phê');
INSERT INTO "industry_codes" VALUES ('0127','Trồng cây chè');
INSERT INTO "industry_codes" VALUES ('0128','Trồng cây gia vị, cây dược liệu, cây hương liệu lâu năm');
INSERT INTO "industry_codes" VALUES ('0129','Trồng cây lâu năm khác');
INSERT INTO "industry_codes" VALUES ('0131','Nhân và chăm sóc cây giống hàng năm');
INSERT INTO "industry_codes" VALUES ('0132','Nhân và chăm sóc cây giống lâu năm');
INSERT INTO "industry_codes" VALUES ('0141','Chăn nuôi trâu, bò và sản xuất giống trâu, bò');
INSERT INTO "industry_codes" VALUES ('0142','Chăn nuôi ngựa, lừa, la và sản xuất giống ngựa, lừa');
INSERT INTO "industry_codes" VALUES ('0144','Chăn nuôi dê, cừu và sản xuất giống dê, cừu, hươu, nai');
INSERT INTO "industry_codes" VALUES ('0145','Chăn nuôi lợn và sản xuất giống lợn');
INSERT INTO "industry_codes" VALUES ('0146','Chăn nuôi gia cầm');
INSERT INTO "industry_codes" VALUES ('0149','Chăn nuôi khác');
INSERT INTO "industry_codes" VALUES ('0150','Trồng trọt, chăn nuôi hỗn hợp');
INSERT INTO "industry_codes" VALUES ('0161','Hoạt động dịch vụ trồng trọt');
INSERT INTO "industry_codes" VALUES ('0162','Hoạt động dịch vụ chăn nuôi');
INSERT INTO "industry_codes" VALUES ('0163','Hoạt động dịch vụ sau thu hoạch');
INSERT INTO "industry_codes" VALUES ('0164','Xử lý hạt giống để nhân giống');
INSERT INTO "industry_codes" VALUES ('0170','Săn bắt, đánh bẫy và hoạt động dịch vụ có liên quan');
INSERT INTO "industry_codes" VALUES ('0210','Trồng rừng, chăm sóc rừng và ươm giống cây lâm nghiệp');
INSERT INTO "industry_codes" VALUES ('0220','Khai thác gỗ');
INSERT INTO "industry_codes" VALUES ('0231','Khai thác lâm sản khác trừ gỗ');
INSERT INTO "industry_codes" VALUES ('0232','Thu nhặt lâm sản khác trừ gỗ');
INSERT INTO "industry_codes" VALUES ('0240','Hoạt động dịch vụ lâm nghiệp');
INSERT INTO "industry_codes" VALUES ('0311','Khai thác thủy sản biển');
INSERT INTO "industry_codes" VALUES ('0312','Khai thác thủy sản nội địa');
INSERT INTO "industry_codes" VALUES ('0321','Nuôi trồng thủy sản biển');
INSERT INTO "industry_codes" VALUES ('0322','Nuôi trồng thủy sản nội địa');
INSERT INTO "industry_codes" VALUES ('0510','Khai thác và thu gom than cứng');
INSERT INTO "industry_codes" VALUES ('0520','Khai thác và thu gom than non');
INSERT INTO "industry_codes" VALUES ('0610','Khai thác dầu thô');
INSERT INTO "industry_codes" VALUES ('0620','Khai thác khí đốt tự nhiên');
INSERT INTO "industry_codes" VALUES ('0710','Khai thác quặng sắt');
INSERT INTO "industry_codes" VALUES ('0721','Khai thác quặng uranium và quặng thorium');
INSERT INTO "industry_codes" VALUES ('0722','Khai thác quặng kim loại khác không chứa sắt');
INSERT INTO "industry_codes" VALUES ('0730','Khai thác quặng kim loại quý hiếm');
INSERT INTO "industry_codes" VALUES ('0810','Khai thác đá, cát, sỏi, đất sét');
INSERT INTO "industry_codes" VALUES ('0891','Khai thác khoáng hoá chất và khoáng phân bón');
INSERT INTO "industry_codes" VALUES ('0892','Khai thác và thu gom than bùn');
INSERT INTO "industry_codes" VALUES ('0893','Khai thác muối');
INSERT INTO "industry_codes" VALUES ('0899','Khai khoáng khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('0910','Hoạt động dịch vụ hỗ trợ khai thác dầu thô và khí tự nhiên');
INSERT INTO "industry_codes" VALUES ('0990','Hoạt động dịch vụ hỗ trợ khai khoáng khác');
INSERT INTO "industry_codes" VALUES ('1010','Chế biến, bảo quản thịt và các sản phẩm từ thịt');
INSERT INTO "industry_codes" VALUES ('1020','Chế biến, bảo quản thuỷ sản và các sản phẩm từ thuỷ sản');
INSERT INTO "industry_codes" VALUES ('1030','Chế biến và bảo quản rau quả');
INSERT INTO "industry_codes" VALUES ('1040','Sản xuất dầu, mỡ động, thực vật');
INSERT INTO "industry_codes" VALUES ('1050','Chế biến sữa và các sản phẩm từ sữa');
INSERT INTO "industry_codes" VALUES ('1061','Xay xát và sản xuất bột thô');
INSERT INTO "industry_codes" VALUES ('1062','Sản xuất tinh bột và các sản phẩm từ tinh bột');
INSERT INTO "industry_codes" VALUES ('1071','Sản xuất các loại bánh từ bột');
INSERT INTO "industry_codes" VALUES ('1072','Sản xuất đường');
INSERT INTO "industry_codes" VALUES ('1073','Sản xuất ca cao, sôcôla và bánh kẹo');
INSERT INTO "industry_codes" VALUES ('1074','Sản xuất mì ống, mỳ sợi và sản phẩm tương tự');
INSERT INTO "industry_codes" VALUES ('1075','Sản xuất món ăn, thức ăn chế biến sẵn');
INSERT INTO "industry_codes" VALUES ('1076','Sản xuất chè');
INSERT INTO "industry_codes" VALUES ('1077','Sản xuất cà phê');
INSERT INTO "industry_codes" VALUES ('1079','Sản xuất thực phẩm khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('1080','Sản xuất thức ăn gia súc, gia cầm và thuỷ sản');
INSERT INTO "industry_codes" VALUES ('1101','Chưng, tinh cất và pha chế các loại rượu mạnh');
INSERT INTO "industry_codes" VALUES ('1102','Sản xuất rượu vang');
INSERT INTO "industry_codes" VALUES ('1103','Sản xuất bia và mạch nha ủ men bia');
INSERT INTO "industry_codes" VALUES ('1104','Sản xuất đồ uống không cồn, nước khoáng');
INSERT INTO "industry_codes" VALUES ('1200','Sản xuất sản phẩm thuốc lá');
INSERT INTO "industry_codes" VALUES ('1311','Sản xuất sợi');
INSERT INTO "industry_codes" VALUES ('1312','Sản xuất vải dệt thoi');
INSERT INTO "industry_codes" VALUES ('1313','Hoàn thiện sản phẩm dệt');
INSERT INTO "industry_codes" VALUES ('1391','Sản xuất vải dệt kim, vải đan móc và vải không dệt khác');
INSERT INTO "industry_codes" VALUES ('1392','Sản xuất hàng dệt sẵn (trừ trang phục)');
INSERT INTO "industry_codes" VALUES ('1393','Sản xuất thảm, chăn, đệm');
INSERT INTO "industry_codes" VALUES ('1394','Sản xuất các loại dây bện và lưới');
INSERT INTO "industry_codes" VALUES ('1399','Sản xuất các loại hàng dệt khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('1410','May trang phục (trừ trang phục từ da lông thú)');
INSERT INTO "industry_codes" VALUES ('1420','Sản xuất sản phẩm từ da lông thú');
INSERT INTO "industry_codes" VALUES ('1430','Sản xuất trang phục dệt kim, đan móc');
INSERT INTO "industry_codes" VALUES ('1511','Thuộc, sơ chế da; sơ chế và nhuộm da lông thú');
INSERT INTO "industry_codes" VALUES ('1512','Sản xuất vali, túi xách và các loại tương tự, sản xuất yên đệm');
INSERT INTO "industry_codes" VALUES ('1520','Sản xuất giày, dép');
INSERT INTO "industry_codes" VALUES ('1610','Cưa, xẻ, bào gỗ và bảo quản gỗ');
INSERT INTO "industry_codes" VALUES ('1621','Sản xuất gỗ dán, gỗ lạng, ván ép và ván mỏng khác');
INSERT INTO "industry_codes" VALUES ('1622','Sản xuất đồ gỗ xây dựng');
INSERT INTO "industry_codes" VALUES ('1623','Sản xuất bao bì bằng gỗ');
INSERT INTO "industry_codes" VALUES ('1629','Sản xuất sản phẩm khác từ gỗ; sản xuất sản phẩm từ tre, nứa, rơm, rạ và vật liệu tết bện');
INSERT INTO "industry_codes" VALUES ('1701','Sản xuất bột giấy, giấy và bìa');
INSERT INTO "industry_codes" VALUES ('1702','Sản xuất giấy nhăn, bìa nhăn, bao bì từ giấy và bìa');
INSERT INTO "industry_codes" VALUES ('1709','Sản xuất các sản phẩm khác từ giấy và bìa chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('1811','In ấn');
INSERT INTO "industry_codes" VALUES ('1812','Dịch vụ liên quan đến in');
INSERT INTO "industry_codes" VALUES ('1820','Sao chép bản ghi các loại');
INSERT INTO "industry_codes" VALUES ('1910','Sản xuất than cốc');
INSERT INTO "industry_codes" VALUES ('1920','Sản xuất sản phẩm dầu mỏ tinh chế');
INSERT INTO "industry_codes" VALUES ('2011','Sản xuất hoá chất cơ bản');
INSERT INTO "industry_codes" VALUES ('2012','Sản xuất phân bón và hợp chất ni tơ');
INSERT INTO "industry_codes" VALUES ('2013','Sản xuất plastic và cao su tổng hợp dạng nguyên sinh');
INSERT INTO "industry_codes" VALUES ('2021','Sản xuất thuốc trừ sâu và sản phẩm hoá chất khác dùng trong nông nghiệp');
INSERT INTO "industry_codes" VALUES ('2022','Sản xuất sơn, véc ni và các chất sơn, quét tương tự; sản xuất mực in và ma tít');
INSERT INTO "industry_codes" VALUES ('2023','Sản xuất mỹ phẩm, xà phòng, chất tẩy rửa, làm bóng và chế phẩm vệ sinh');
INSERT INTO "industry_codes" VALUES ('2029','Sản xuất sản phẩm hoá chất khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('2030','Sản xuất sợi nhân tạo');
INSERT INTO "industry_codes" VALUES ('2100','Sản xuất thuốc, hoá dược và dược liệu');
INSERT INTO "industry_codes" VALUES ('2211','Sản xuất săm, lốp cao su; đắp và tái chế lốp cao su');
INSERT INTO "industry_codes" VALUES ('2219','Sản xuất sản phẩm khác từ cao su');
INSERT INTO "industry_codes" VALUES ('2220','Sản xuất sản phẩm từ plastic');
INSERT INTO "industry_codes" VALUES ('2310','Sản xuất thủy tinh và sản phẩm từ thủy tinh');
INSERT INTO "industry_codes" VALUES ('2391','Sản xuất sản phẩm chịu lửa');
INSERT INTO "industry_codes" VALUES ('2392','Sản xuất vật liệu xây dựng từ đất sét');
INSERT INTO "industry_codes" VALUES ('2393','Sản xuất sản phẩm gốm sứ khác');
INSERT INTO "industry_codes" VALUES ('2394','Sản xuất xi măng, vôi và thạch cao');
INSERT INTO "industry_codes" VALUES ('2395','Sản xuất bê tông và các sản phẩm từ bê tông, xi măng và thạch cao');
INSERT INTO "industry_codes" VALUES ('2396','Cắt tạo dáng và hoàn thiện đá');
INSERT INTO "industry_codes" VALUES ('2399','Sản xuất sản phẩm từ chất khoáng phi kim loại khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('2410','Sản xuất sắt, thép, gang');
INSERT INTO "industry_codes" VALUES ('2420','Sản xuất kim loại quý và kim loại màu');
INSERT INTO "industry_codes" VALUES ('2431','Đúc sắt, thép');
INSERT INTO "industry_codes" VALUES ('2432','Đúc kim loại màu');
INSERT INTO "industry_codes" VALUES ('2511','Sản xuất các cấu kiện kim loại');
INSERT INTO "industry_codes" VALUES ('2512','Sản xuất thùng, bể chứa và dụng cụ chứa đựng bằng kim loại');
INSERT INTO "industry_codes" VALUES ('2513','Sản xuất nồi hơi (trừ nồi hơi trung tâm)');
INSERT INTO "industry_codes" VALUES ('2520','Sản xuất vũ khí và đạn dược');
INSERT INTO "industry_codes" VALUES ('2591','Rèn, dập, ép và cán kim loại; luyện bột kim loại');
INSERT INTO "industry_codes" VALUES ('2592','Gia công cơ khí; xử lý và tráng phủ kim loại');
INSERT INTO "industry_codes" VALUES ('2593','Sản xuất dao kéo, dụng cụ cầm tay và đồ kim loại thông dụng');
INSERT INTO "industry_codes" VALUES ('2599','Sản xuất sản phẩm khác bằng kim loại chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('2610','Sản xuất linh kiện điện tử');
INSERT INTO "industry_codes" VALUES ('2620','Sản xuất máy vi tính và thiết bị ngoại vi của máy vi tính');
INSERT INTO "industry_codes" VALUES ('2630','Sản xuất thiết bị truyền thông');
INSERT INTO "industry_codes" VALUES ('2640','Sản xuất sản phẩm điện tử dân dụng');
INSERT INTO "industry_codes" VALUES ('2651','Sản xuất thiết bị đo lường, kiểm tra, định hướng và điều khiển');
INSERT INTO "industry_codes" VALUES ('2652','Sản xuất đồng hồ');
INSERT INTO "industry_codes" VALUES ('2660','Sản xuất thiết bị bức xạ, thiết bị điện tử trong y học, điện liệu pháp');
INSERT INTO "industry_codes" VALUES ('2670','Sản xuất thiết bị và dụng cụ quang học');
INSERT INTO "industry_codes" VALUES ('2680','Sản xuất băng, đĩa từ tính và quang học');
INSERT INTO "industry_codes" VALUES ('2710','Sản xuất mô tơ, máy phát, biến thế điện, thiết bị phân phối và điều khiển điện');
INSERT INTO "industry_codes" VALUES ('2720','Sản xuất pin và ắc quy');
INSERT INTO "industry_codes" VALUES ('2731','Sản xuất dây cáp, sợi cáp quang học');
INSERT INTO "industry_codes" VALUES ('2732','Sản xuất dây, cáp điện và điện tử khác');
INSERT INTO "industry_codes" VALUES ('2733','Sản xuất thiết bị dây dẫn điện các loại');
INSERT INTO "industry_codes" VALUES ('2740','Sản xuất thiết bị điện chiếu sáng');
INSERT INTO "industry_codes" VALUES ('2750','Sản xuất đồ điện dân dụng');
INSERT INTO "industry_codes" VALUES ('2790','Sản xuất thiết bị điện khác');
INSERT INTO "industry_codes" VALUES ('2811','Sản xuất động cơ, tua bin (trừ động cơ máy bay, ô tô, mô tô và xe máy)');
INSERT INTO "industry_codes" VALUES ('2812','Sản xuất thiết bị sử dụng năng lượng chiết lưu');
INSERT INTO "industry_codes" VALUES ('2813','Sản xuất máy bơm, máy nén, vòi và van khác');
INSERT INTO "industry_codes" VALUES ('2814','Sản xuất bi, bánh răng, hộp số, các bộ phận điều khiển và truyền chuyển động');
INSERT INTO "industry_codes" VALUES ('2815','Sản xuất lò nướng, lò luyện và lò nung');
INSERT INTO "industry_codes" VALUES ('2816','Sản xuất các thiết bị nâng, hạ và bốc xếp');
INSERT INTO "industry_codes" VALUES ('2817','Sản xuất máy móc và thiết bị văn phòng (trừ máy vi tính và thiết bị ngoại vi của máy vi tính)');
INSERT INTO "industry_codes" VALUES ('2818','Sản xuất dụng cụ cầm tay chạy bằng mô tơ hoặc khí nén');
INSERT INTO "industry_codes" VALUES ('2819','Sản xuất máy thông dụng khác');
INSERT INTO "industry_codes" VALUES ('2821','Sản xuất máy nông nghiệp và lâm nghiệp');
INSERT INTO "industry_codes" VALUES ('2822','Sản xuất máy công cụ và máy tạo hình kim loại');
INSERT INTO "industry_codes" VALUES ('2823','Sản xuất máy luyện kim');
INSERT INTO "industry_codes" VALUES ('2824','Sản xuất máy khai thác mỏ và xây dựng');
INSERT INTO "industry_codes" VALUES ('2825','Sản xuất máy chế biến thực phẩm, đồ uống và thuốc lá');
INSERT INTO "industry_codes" VALUES ('2826','Sản xuất máy cho ngành dệt, may và da');
INSERT INTO "industry_codes" VALUES ('2829','Sản xuất máy chuyên dụng khác');
INSERT INTO "industry_codes" VALUES ('2910','Sản xuất ô tô và xe có động cơ khác');
INSERT INTO "industry_codes" VALUES ('2920','Sản xuất thân xe ô tô và xe có động cơ khác, rơ moóc và bán rơ moóc');
INSERT INTO "industry_codes" VALUES ('2930','Sản xuất phụ tùng và bộ phận phụ trợ cho xe ô tô và xe có động cơ khác');
INSERT INTO "industry_codes" VALUES ('3011','Đóng tàu và cấu kiện nổi');
INSERT INTO "industry_codes" VALUES ('3012','Đóng thuyền, xuồng thể thao và giải trí');
INSERT INTO "industry_codes" VALUES ('3020','Sản xuất đầu máy xe lửa, xe điện và toa xe');
INSERT INTO "industry_codes" VALUES ('3030','Sản xuất máy bay, tàu vũ trụ và máy móc liên quan');
INSERT INTO "industry_codes" VALUES ('3040','Sản xuất xe cơ giới chiến đấu dùng trong quân đội');
INSERT INTO "industry_codes" VALUES ('3091','Sản xuất mô tô, xe máy');
INSERT INTO "industry_codes" VALUES ('3092','Sản xuất xe đạp và xe cho người khuyết tật');
INSERT INTO "industry_codes" VALUES ('3099','Sản xuất phương tiện và thiết bị vận tải khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('3100','Sản xuất giường, tủ, bàn, ghế');
INSERT INTO "industry_codes" VALUES ('3211','Sản xuất đồ kim hoàn và chi tiết liên quan');
INSERT INTO "industry_codes" VALUES ('3212','Sản xuất đồ giả kim hoàn và chi tiết liên quan');
INSERT INTO "industry_codes" VALUES ('3220','Sản xuất nhạc cụ');
INSERT INTO "industry_codes" VALUES ('3230','Sản xuất dụng cụ thể dục, thể thao');
INSERT INTO "industry_codes" VALUES ('3240','Sản xuất đồ chơi, trò chơi');
INSERT INTO "industry_codes" VALUES ('3250','Sản xuất thiết bị, dụng cụ y tế, nha khoa, chỉnh hình và phục hồi chức năng');
INSERT INTO "industry_codes" VALUES ('3290','Sản xuất khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('3311','Sửa chữa các sản phẩm kim loại đúc sẵn');
INSERT INTO "industry_codes" VALUES ('3312','Sửa chữa máy móc, thiết bị');
INSERT INTO "industry_codes" VALUES ('3313','Sửa chữa thiết bị điện tử và quang học');
INSERT INTO "industry_codes" VALUES ('3314','Sửa chữa thiết bị điện');
INSERT INTO "industry_codes" VALUES ('3315','Sửa chữa và bảo dưỡng phương tiện vận tải (trừ ô tô, mô tô, xe máy và xe có động cơ khác)');
INSERT INTO "industry_codes" VALUES ('3319','Sửa chữa thiết bị khác');
INSERT INTO "industry_codes" VALUES ('3320','Lắp đặt máy móc và thiết bị công nghiệp');
INSERT INTO "industry_codes" VALUES ('3511','Sản xuất điện');
INSERT INTO "industry_codes" VALUES ('3512','Truyền tải và phân phối điện');
INSERT INTO "industry_codes" VALUES ('3520','Sản xuất khí đốt, phân phối nhiên liệu khí bằng đường ống');
INSERT INTO "industry_codes" VALUES ('3530','Sản xuất, phân phối hơi nước, nước nóng, điều hoà không khí và sản xuất nước đá');
INSERT INTO "industry_codes" VALUES ('3600','Khai thác, xử lý và cung cấp nước');
INSERT INTO "industry_codes" VALUES ('3700','Thoát nước và xử lý nước thải');
INSERT INTO "industry_codes" VALUES ('3811','Thu gom rác thải không độc hại');
INSERT INTO "industry_codes" VALUES ('3812','Thu gom rác thải độc hại');
INSERT INTO "industry_codes" VALUES ('3821','Xử lý và tiêu hủy rác thải không độc hại');
INSERT INTO "industry_codes" VALUES ('3822','Xử lý và tiêu hủy rác thải độc hại');
INSERT INTO "industry_codes" VALUES ('3830','Tái chế phế liệu');
INSERT INTO "industry_codes" VALUES ('3900','Xử lý ô nhiễm và hoạt động quản lý chất thải khác');
INSERT INTO "industry_codes" VALUES ('4101','Xây dựng nhà để ở');
INSERT INTO "industry_codes" VALUES ('4102','Xây dựng nhà không để ở');
INSERT INTO "industry_codes" VALUES ('4211','Xây dựng công trình đường sắt');
INSERT INTO "industry_codes" VALUES ('4212','Xây dựng công trình đường bộ');
INSERT INTO "industry_codes" VALUES ('4221','Xây dựng công trình điện');
INSERT INTO "industry_codes" VALUES ('4222','Xây dựng công trình cấp, thoát nước');
INSERT INTO "industry_codes" VALUES ('4223','Xây dựng công trình viễn thông, thông tin liên lạc');
INSERT INTO "industry_codes" VALUES ('4229','Xây dựng công trình công ích khác');
INSERT INTO "industry_codes" VALUES ('4291','Xây dựng công trình thủy');
INSERT INTO "industry_codes" VALUES ('4292','Xây dựng công trình khai khoáng');
INSERT INTO "industry_codes" VALUES ('4293','Xây dựng công trình chế biến, chế tạo');
INSERT INTO "industry_codes" VALUES ('4299','Xây dựng công trình kỹ thuật dân dụng khác');
INSERT INTO "industry_codes" VALUES ('4311','Phá dỡ');
INSERT INTO "industry_codes" VALUES ('4312','Chuẩn bị mặt bằng');
INSERT INTO "industry_codes" VALUES ('4321','Lắp đặt hệ thống điện');
INSERT INTO "industry_codes" VALUES ('4322','Lắp đặt hệ thống cấp, thoát nước, hệ thống sưởi và điều hoà không khí');
INSERT INTO "industry_codes" VALUES ('4329','Lắp đặt hệ thống xây dựng khác');
INSERT INTO "industry_codes" VALUES ('4330','Hoàn thiện công trình xây dựng');
INSERT INTO "industry_codes" VALUES ('4390','Hoạt động xây dựng chuyên dụng khác');
INSERT INTO "industry_codes" VALUES ('4511','Bán buôn ô tô và xe có động cơ khác');
INSERT INTO "industry_codes" VALUES ('4512','Bán lẻ ô tô con (loại 9 chỗ ngồi trở xuống)');
INSERT INTO "industry_codes" VALUES ('4513','Đại lý ô tô và xe có động cơ khác');
INSERT INTO "industry_codes" VALUES ('4520','Bảo dưỡng, sửa chữa ô tô và xe có động cơ khác');
INSERT INTO "industry_codes" VALUES ('4530','Bán phụ tùng và các bộ phận phụ trợ của ô tô và xe có động cơ khác');
INSERT INTO "industry_codes" VALUES ('4541','Bán mô tô, xe máy');
INSERT INTO "industry_codes" VALUES ('4542','Bảo dưỡng và sửa chữa mô tô, xe máy');
INSERT INTO "industry_codes" VALUES ('4543','Bán phụ tùng và các bộ phận phụ trợ của mô tô, xe máy');
INSERT INTO "industry_codes" VALUES ('4610','Đại lý, môi giới, đấu giá hàng hóa');
INSERT INTO "industry_codes" VALUES ('4620','Bán buôn nông, lâm sản nguyên liệu (trừ gỗ, tre, nứa) và động vật sống');
INSERT INTO "industry_codes" VALUES ('4631','Bán buôn gạo, lúa mỳ, hạt ngũ cốc khác, bột mỳ');
INSERT INTO "industry_codes" VALUES ('4632','Bán buôn thực phẩm');
INSERT INTO "industry_codes" VALUES ('4633','Bán buôn đồ uống');
INSERT INTO "industry_codes" VALUES ('4634','Bán buôn sản phẩm thuốc lá, thuốc lào');
INSERT INTO "industry_codes" VALUES ('4641','Bán buôn vải, hàng may mặc, giày dép');
INSERT INTO "industry_codes" VALUES ('4649','Bán buôn đồ dùng khác cho gia đình');
INSERT INTO "industry_codes" VALUES ('4651','Bán buôn máy vi tính, thiết bị ngoại vi và phần mềm');
INSERT INTO "industry_codes" VALUES ('4652','Bán buôn thiết bị và linh kiện điện tử, viễn thông');
INSERT INTO "industry_codes" VALUES ('4653','Bán buôn máy móc, thiết bị và phụ tùng máy nông nghiệp');
INSERT INTO "industry_codes" VALUES ('4659','Bán buôn máy móc, thiết bị và phụ tùng máy khác');
INSERT INTO "industry_codes" VALUES ('4661','Bán buôn nhiên liệu rắn, lỏng, khí và các sản phẩm liên quan');
INSERT INTO "industry_codes" VALUES ('4662','Bán buôn kim loại và quặng kim loại');
INSERT INTO "industry_codes" VALUES ('4663','Bán buôn vật liệu, thiết bị lắp đặt khác trong xây dựng');
INSERT INTO "industry_codes" VALUES ('4669','Bán buôn chuyên doanh khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('4690','Bán buôn tổng hợp');
INSERT INTO "industry_codes" VALUES ('4711','Bán lẻ lương thực, thực phẩm, đồ uống, thuốc lá, thuốc lào chiếm tỷ trọng lớn trong các cửa hàng kinh doanh tổng hợp');
INSERT INTO "industry_codes" VALUES ('4719','Bán lẻ khác trong các cửa hàng kinh doanh tổng hợp');
INSERT INTO "industry_codes" VALUES ('4721','Bán lẻ lương thực trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4722','Bán lẻ thực phẩm trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4723','Bán lẻ đồ uống trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4724','Bán lẻ sản phẩm thuốc lá, thuốc lào trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4730','Bán lẻ nhiên liệu động cơ trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4741','Bán lẻ máy vi tính, thiết bị ngoại vi, phần mềm và thiết bị viễn thông trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4742','Bán lẻ thiết bị nghe nhìn trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4751','Bán lẻ vải, len, sợi, chỉ khâu và hàng dệt khác trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4752','Bán lẻ đồ ngũ kim, sơn, kính và thiết bị lắp đặt khác trong xây dựng trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4753','Bán lẻ thảm, đệm, chăn, màn, rèm, vật liệu phủ tường và sàn trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4759','Bán lẻ đồ điện gia dụng, giường, tủ, bàn, ghế và đồ nội thất tương tự, đèn và bộ đèn điện, đồ dùng gia đình khác chưa được phân vào đâu trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4761','Bán lẻ sách, báo, tạp chí văn phòng phẩm trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4762','Bán lẻ băng đĩa âm thanh, hình ảnh (kể cả băng, đĩa trắng) trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4763','Bán lẻ thiết bị, dụng cụ thể dục, thể thao trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4764','Bán lẻ trò chơi, đồ chơi trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4771','Bán lẻ hàng may mặc, giày dép, hàng da và giả da trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4772','Bán lẻ thuốc, dụng cụ y tế, mỹ phẩm và vật phẩm vệ sinh trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4773','Bán lẻ hàng hóa khác mới trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4774','Bán lẻ hàng hóa đã qua sử dụng trong các cửa hàng chuyên doanh');
INSERT INTO "industry_codes" VALUES ('4781','Bán lẻ lương thực, thực phẩm, đồ uống, thuốc lá, thuốc lào lưu động hoặc tại chợ');
INSERT INTO "industry_codes" VALUES ('4782','Bán lẻ hàng dệt, may sẵn, giày dép lưu động hoặc tại chợ');
INSERT INTO "industry_codes" VALUES ('4783','Bán lẻ thiết bị công nghệ thông tin liên lạc lưu động hoặc tại chợ');
INSERT INTO "industry_codes" VALUES ('4784','Bán lẻ thiết bị gia đình khác lưu động hoặc tại chợ');
INSERT INTO "industry_codes" VALUES ('4785','Bán lẻ hàng văn hóa, giải trí lưu động hoặc tại chợ');
INSERT INTO "industry_codes" VALUES ('4789','Bán lẻ hàng hóa khác lưu động hoặc tại chợ');
INSERT INTO "industry_codes" VALUES ('4791','Bán lẻ theo yêu cầu đặt hàng qua bưu điện hoặc internet');
INSERT INTO "industry_codes" VALUES ('4799','Bán lẻ hình thức khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('4911','Vận tải hành khách đường sắt');
INSERT INTO "industry_codes" VALUES ('4912','Vận tải hàng hóa đường sắt');
INSERT INTO "industry_codes" VALUES ('4921','Vận tải hành khách bằng xe buýt trong nội thành');
INSERT INTO "industry_codes" VALUES ('4922','Vận tải hành khách bằng xe buýt giữa nội thành và ngoại thành, liên tỉnh');
INSERT INTO "industry_codes" VALUES ('4929','Vận tải hành khách bằng xe buýt loại khác');
INSERT INTO "industry_codes" VALUES ('4931','Vận tải hành khách đường bộ trong nội thành, ngoại thành (trừ vận tải bằng xe buýt)');
INSERT INTO "industry_codes" VALUES ('4932','Vận tải hành khách đường bộ khác');
INSERT INTO "industry_codes" VALUES ('4933','Vận tải hàng hóa bằng đường bộ');
INSERT INTO "industry_codes" VALUES ('4940','Vận tải đường ống');
INSERT INTO "industry_codes" VALUES ('5011','Vận tải hành khách ven biển và viễn dương');
INSERT INTO "industry_codes" VALUES ('5012','Vận tải hàng hóa ven biển và viễn dương');
INSERT INTO "industry_codes" VALUES ('5021','Vận tải hành khách đường thủy nội địa');
INSERT INTO "industry_codes" VALUES ('5022','Vận tải hàng hóa đường thủy nội địa');
INSERT INTO "industry_codes" VALUES ('5110','Vận tải hành khách hàng không');
INSERT INTO "industry_codes" VALUES ('5120','Vận tải hàng hóa hàng không');
INSERT INTO "industry_codes" VALUES ('5210','Kho bãi và lưu giữ hàng hóa');
INSERT INTO "industry_codes" VALUES ('5221','Hoạt động dịch vụ hỗ trợ trực tiếp cho vận tải đường sắt');
INSERT INTO "industry_codes" VALUES ('5222','Hoạt động dịch vụ hỗ trợ trực tiếp cho vận tải đường thủy');
INSERT INTO "industry_codes" VALUES ('5223','Hoạt động dịch vụ hỗ trợ trực tiếp cho vận tải hàng không');
INSERT INTO "industry_codes" VALUES ('5224','Bốc xếp hàng hóa');
INSERT INTO "industry_codes" VALUES ('5225','Hoạt động dịch vụ hỗ trợ trực tiếp cho vận tải đường bộ');
INSERT INTO "industry_codes" VALUES ('5229','Hoạt động dịch vụ hỗ trợ khác liên quan đến vận tải');
INSERT INTO "industry_codes" VALUES ('5310','Bưu chính');
INSERT INTO "industry_codes" VALUES ('5320','Chuyển phát');
INSERT INTO "industry_codes" VALUES ('5510','Dịch vụ lưu trú ngắn ngày');
INSERT INTO "industry_codes" VALUES ('5590','Cơ sở lưu trú khác');
INSERT INTO "industry_codes" VALUES ('5610','Nhà hàng và các dịch vụ ăn uống phục vụ lưu động');
INSERT INTO "industry_codes" VALUES ('5621','Cung cấp dịch vụ ăn uống theo hợp đồng không thường xuyên với khách hàng');
INSERT INTO "industry_codes" VALUES ('5629','Dịch vụ ăn uống khác');
INSERT INTO "industry_codes" VALUES ('5630','Dịch vụ phục vụ đồ uống');
INSERT INTO "industry_codes" VALUES ('5811','Xuất bản sách');
INSERT INTO "industry_codes" VALUES ('5812','Xuất bản các danh mục chỉ dẫn và địa chỉ');
INSERT INTO "industry_codes" VALUES ('5813','Xuất bản báo, tạp chí và các ấn phẩm định kỳ');
INSERT INTO "industry_codes" VALUES ('5819','Hoạt động xuất bản khác');
INSERT INTO "industry_codes" VALUES ('5820','Xuất bản phần mềm');
INSERT INTO "industry_codes" VALUES ('5911','Hoạt động sản xuất phim điện ảnh, phim video và chương trình truyền hình');
INSERT INTO "industry_codes" VALUES ('5912','Hoạt động hậu kỳ');
INSERT INTO "industry_codes" VALUES ('5913','Hoạt động phát hành phim điện ảnh, phim video và chương trình truyền hình');
INSERT INTO "industry_codes" VALUES ('5914','Hoạt động chiếu phim');
INSERT INTO "industry_codes" VALUES ('5920','Hoạt động ghi âm và xuất bản âm nhạc');
INSERT INTO "industry_codes" VALUES ('6010','Hoạt động phát thanh');
INSERT INTO "industry_codes" VALUES ('6021','Hoạt động truyền hình');
INSERT INTO "industry_codes" VALUES ('6022','Chương trình cáp, vệ tinh và các chương trình thuê bao khác');
INSERT INTO "industry_codes" VALUES ('6110','Hoạt động viễn thông có dây');
INSERT INTO "industry_codes" VALUES ('6120','Hoạt động viễn thông không dây');
INSERT INTO "industry_codes" VALUES ('6130','Hoạt động viễn thông vệ tinh');
INSERT INTO "industry_codes" VALUES ('6190','Hoạt động viễn thông khác');
INSERT INTO "industry_codes" VALUES ('6201','Lập trình máy vi tính');
INSERT INTO "industry_codes" VALUES ('6202','Tư vấn máy vi tính và quản trị hệ thống máy vi tính');
INSERT INTO "industry_codes" VALUES ('6209','Hoạt động dịch vụ công nghệ thông tin và dịch vụ khác liên quan đến máy vi tính');
INSERT INTO "industry_codes" VALUES ('6311','Xử lý dữ liệu, cho thuê và các hoạt động liên quan');
INSERT INTO "industry_codes" VALUES ('6312','Cổng thông tin');
INSERT INTO "industry_codes" VALUES ('6391','Hoạt động thông tấn');
INSERT INTO "industry_codes" VALUES ('6399','Dịch vụ thông tin khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('6411','Hoạt động ngân hàng trung ương');
INSERT INTO "industry_codes" VALUES ('6419','Hoạt động trung gian tiền tệ khác');
INSERT INTO "industry_codes" VALUES ('6420','Hoạt động công ty nắm giữ tài sản');
INSERT INTO "industry_codes" VALUES ('6430','Hoạt động quỹ tín thác, các quỹ và các tổ chức tài chính khác');
INSERT INTO "industry_codes" VALUES ('6491','Hoạt động cho thuê tài chính');
INSERT INTO "industry_codes" VALUES ('6492','Hoạt động cấp tín dụng khác');
INSERT INTO "industry_codes" VALUES ('6499','Hoạt động dịch vụ tài chính khác chưa được phân vào đâu (trừ bảo hiểm và bảo hiểm xã hội)');
INSERT INTO "industry_codes" VALUES ('6511','Bảo hiểm nhân thọ');
INSERT INTO "industry_codes" VALUES ('6512','Bảo hiểm phi nhân thọ');
INSERT INTO "industry_codes" VALUES ('6513','Bảo hiểm sức khỏe');
INSERT INTO "industry_codes" VALUES ('6520','Tái bảo hiểm');
INSERT INTO "industry_codes" VALUES ('6530','Bảo hiểm xã hội');
INSERT INTO "industry_codes" VALUES ('6611','Quản lý thị trường tài chính');
INSERT INTO "industry_codes" VALUES ('6612','Môi giới hợp đồng hàng hóa và chứng khoán');
INSERT INTO "industry_codes" VALUES ('6619','Hoạt động hỗ trợ dịch vụ tài chính chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('6621','Đánh giá rủi ro và thiệt hại');
INSERT INTO "industry_codes" VALUES ('6622','Hoạt động của đại lý và môi giới bảo hiểm');
INSERT INTO "industry_codes" VALUES ('6629','Hoạt động hỗ trợ khác cho bảo hiểm và bảo hiểm xã hội');
INSERT INTO "industry_codes" VALUES ('6630','Hoạt động quản lý quỹ');
INSERT INTO "industry_codes" VALUES ('6810','Kinh doanh bất động sản, quyền sử dụng đất thuộc chủ sở hữu, chủ sử dụng hoặc đi thuê');
INSERT INTO "industry_codes" VALUES ('6820','Tư vấn, môi giới, đấu giá bất động sản, đấu giá quyền sử dụng đất');
INSERT INTO "industry_codes" VALUES ('6910','Hoạt động pháp luật');
INSERT INTO "industry_codes" VALUES ('6920','Hoạt động liên quan đến kế toán, kiểm toán và tư vấn về thuế');
INSERT INTO "industry_codes" VALUES ('7010','Hoạt động của trụ sở văn phòng');
INSERT INTO "industry_codes" VALUES ('7020','Hoạt động tư vấn quản lý');
INSERT INTO "industry_codes" VALUES ('7110','Hoạt động kiến trúc và tư vấn kỹ thuật có liên quan');
INSERT INTO "industry_codes" VALUES ('7120','Kiểm tra và phân tích kỹ thuật');
INSERT INTO "industry_codes" VALUES ('7211','Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực khoa học tự nhiên');
INSERT INTO "industry_codes" VALUES ('7212','Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực khoa học kỹ thuật và công nghệ');
INSERT INTO "industry_codes" VALUES ('7213','Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực khoa học y, dược');
INSERT INTO "industry_codes" VALUES ('7214','Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực khoa học nông nghiệp');
INSERT INTO "industry_codes" VALUES ('7221','Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực khoa học xã hội');
INSERT INTO "industry_codes" VALUES ('7222','Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực khoa học nhân văn');
INSERT INTO "industry_codes" VALUES ('7310','Quảng cáo');
INSERT INTO "industry_codes" VALUES ('7320','Nghiên cứu thị trường và thăm dò dư luận');
INSERT INTO "industry_codes" VALUES ('7410','Hoạt động thiết kế chuyên dụng');
INSERT INTO "industry_codes" VALUES ('7420','Hoạt động nhiếp ảnh');
INSERT INTO "industry_codes" VALUES ('7490','Hoạt động chuyên môn, khoa học và công nghệ khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('7500','Hoạt động thú y');
INSERT INTO "industry_codes" VALUES ('7710','Cho thuê xe có động cơ');
INSERT INTO "industry_codes" VALUES ('7721','Cho thuê thiết bị thể thao, vui chơi giải trí');
INSERT INTO "industry_codes" VALUES ('7722','Cho thuê băng, đĩa video');
INSERT INTO "industry_codes" VALUES ('7729','Cho thuê đồ dùng cá nhân và gia đình khác');
INSERT INTO "industry_codes" VALUES ('7730','Cho thuê máy móc, thiết bị và đồ dùng hữu hình khác không kèm người điều khiển');
INSERT INTO "industry_codes" VALUES ('7740','Cho thuê tài sản vô hình phi tài chính');
INSERT INTO "industry_codes" VALUES ('7810','Hoạt động của các trung tâm, đại lý tư vấn, giới thiệu và môi giới lao động, việc làm');
INSERT INTO "industry_codes" VALUES ('7820','Cung ứng lao động tạm thời');
INSERT INTO "industry_codes" VALUES ('7830','Cung ứng và quản lý nguồn lao động');
INSERT INTO "industry_codes" VALUES ('7911','Đại lý du lịch');
INSERT INTO "industry_codes" VALUES ('7912','Điều hành tua du lịch');
INSERT INTO "industry_codes" VALUES ('7990','Dịch vụ đặt chỗ và các dịch vụ hỗ trợ liên quan đến quảng bá và tổ chức tua du lịch');
INSERT INTO "industry_codes" VALUES ('8010','Hoạt động bảo vệ tư nhân');
INSERT INTO "industry_codes" VALUES ('8020','Dịch vụ hệ thống bảo đảm an toàn');
INSERT INTO "industry_codes" VALUES ('8030','Dịch vụ điều tra');
INSERT INTO "industry_codes" VALUES ('8110','Dịch vụ hỗ trợ tổng hợp');
INSERT INTO "industry_codes" VALUES ('8121','Vệ sinh chung nhà cửa');
INSERT INTO "industry_codes" VALUES ('8129','Vệ sinh công nghiệp và các công trình chuyên biệt');
INSERT INTO "industry_codes" VALUES ('8130','Dịch vụ chăm sóc và duy trì cảnh quan');
INSERT INTO "industry_codes" VALUES ('8211','Dịch vụ hành chính văn phòng tổng hợp');
INSERT INTO "industry_codes" VALUES ('8219','Photo, chuẩn bị tài liệu và các hoạt động hỗ trợ văn phòng đặc biệt khác');
INSERT INTO "industry_codes" VALUES ('8220','Hoạt động dịch vụ liên quan đến các cuộc gọi');
INSERT INTO "industry_codes" VALUES ('8230','Tổ chức giới thiệu và xúc tiến thương mại');
INSERT INTO "industry_codes" VALUES ('8291','Hoạt động dịch vụ hỗ trợ thanh toán, tín dụng');
INSERT INTO "industry_codes" VALUES ('8292','Dịch vụ đóng gói');
INSERT INTO "industry_codes" VALUES ('8299','Hoạt động dịch vụ hỗ trợ kinh doanh khác còn lại chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('8411','Hoạt động của Đảng cộng sản, tổ chức chính trị - xã hội, hoạt động quản lý nhà nước nói chung và kinh tế tổng hợp');
INSERT INTO "industry_codes" VALUES ('8412','Hoạt động quản lý nhà nước trong các lĩnh vực y tế, giáo dục, văn hóa và các dịch vụ xã hội khác (trừ bảo đảm xã hội bắt buộc)');
INSERT INTO "industry_codes" VALUES ('8413','Hoạt động quản lý nhà nước trong các lĩnh vực kinh tế chuyên ngành');
INSERT INTO "industry_codes" VALUES ('8421','Hoạt động đối ngoại');
INSERT INTO "industry_codes" VALUES ('8422','Hoạt động quốc phòng');
INSERT INTO "industry_codes" VALUES ('8423','Hoạt động an ninh, trật tự an toàn xã hội');
INSERT INTO "industry_codes" VALUES ('8430','Hoạt động bảo đảm xã hội bắt buộc');
INSERT INTO "industry_codes" VALUES ('8511','Giáo dục nhà trẻ');
INSERT INTO "industry_codes" VALUES ('8512','Giáo dục mẫu giáo');
INSERT INTO "industry_codes" VALUES ('8521','Giáo dục tiểu học');
INSERT INTO "industry_codes" VALUES ('8522','Giáo dục trung học cơ sở');
INSERT INTO "industry_codes" VALUES ('8523','Giáo dục trung học phổ thông');
INSERT INTO "industry_codes" VALUES ('8531','Đào tạo sơ cấp');
INSERT INTO "industry_codes" VALUES ('8532','Đào tạo trung cấp');
INSERT INTO "industry_codes" VALUES ('8533','Đào tạo cao đẳng');
INSERT INTO "industry_codes" VALUES ('8541','Đào tạo đại học');
INSERT INTO "industry_codes" VALUES ('8542','Đào tạo thạc sỹ');
INSERT INTO "industry_codes" VALUES ('8543','Đào tạo tiến sỹ');
INSERT INTO "industry_codes" VALUES ('8551','Giáo dục thể thao và giải trí');
INSERT INTO "industry_codes" VALUES ('8552','Giáo dục văn hóa nghệ thuật');
INSERT INTO "industry_codes" VALUES ('8559','Giáo dục khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('8560','Dịch vụ hỗ trợ giáo dục');
INSERT INTO "industry_codes" VALUES ('8610','Hoạt động của các bệnh viện, trạm y tế');
INSERT INTO "industry_codes" VALUES ('8620','Hoạt động của các phòng khám đa khoa, chuyên khoa và nha khoa');
INSERT INTO "industry_codes" VALUES ('8691','Hoạt động y tế dự phòng');
INSERT INTO "industry_codes" VALUES ('8692','Hoạt động của hệ thống cơ sở chỉnh hình, phục hồi chức năng');
INSERT INTO "industry_codes" VALUES ('8699','Hoạt động y tế khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('8710','Hoạt động của các cơ sở nuôi dưỡng, điều dưỡng');
INSERT INTO "industry_codes" VALUES ('8720','Hoạt động chăm sóc sức khoẻ người bị thiểu năng, tâm thần và người nghiện');
INSERT INTO "industry_codes" VALUES ('8730','Hoạt động chăm sóc sức khoẻ người có công, người già và người khuyết tật không có khả năng tự chăm sóc');
INSERT INTO "industry_codes" VALUES ('8790','Hoạt động chăm sóc tập trung khác');
INSERT INTO "industry_codes" VALUES ('8810','Hoạt động trợ giúp xã hội không tập trung đối với người có công, thương bệnh binh, người già và người khuyết tật');
INSERT INTO "industry_codes" VALUES ('8890','Hoạt động trợ giúp xã hội không tập trung khác');
INSERT INTO "industry_codes" VALUES ('9000','Hoạt động sáng tác, nghệ thuật và giải trí');
INSERT INTO "industry_codes" VALUES ('9101','Hoạt động thư viện và lưu trữ');
INSERT INTO "industry_codes" VALUES ('9102','Hoạt động bảo tồn, bảo tàng');
INSERT INTO "industry_codes" VALUES ('9103','Hoạt động của các vườn bách thảo, bách thú và khu bảo tồn tự nhiên');
INSERT INTO "industry_codes" VALUES ('9200','Hoạt động xổ số, cá cược và đánh bạc');
INSERT INTO "industry_codes" VALUES ('9311','Hoạt động của các cơ sở thể thao');
INSERT INTO "industry_codes" VALUES ('9312','Hoạt động của các câu lạc bộ thể thao');
INSERT INTO "industry_codes" VALUES ('9319','Hoạt động thể thao khác');
INSERT INTO "industry_codes" VALUES ('9321','Hoạt động của các công viên vui chơi và công viên theo chủ đề');
INSERT INTO "industry_codes" VALUES ('9329','Hoạt động vui chơi giải trí khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('9411','Hoạt động của các hiệp hội kinh doanh và nghiệp chủ');
INSERT INTO "industry_codes" VALUES ('9412','Hoạt động của các hội nghề nghiệp');
INSERT INTO "industry_codes" VALUES ('9420','Hoạt động của công đoàn');
INSERT INTO "industry_codes" VALUES ('9491','Hoạt động của các tổ chức tôn giáo');
INSERT INTO "industry_codes" VALUES ('9499','Hoạt động của các tổ chức khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('9511','Sửa chữa máy vi tính và thiết bị ngoại vi');
INSERT INTO "industry_codes" VALUES ('9512','Sửa chữa thiết bị liên lạc');
INSERT INTO "industry_codes" VALUES ('9521','Sửa chữa thiết bị nghe nhìn điện tử gia dụng');
INSERT INTO "industry_codes" VALUES ('9522','Sửa chữa thiết bị, đồ dùng gia đình');
INSERT INTO "industry_codes" VALUES ('9523','Sửa chữa giày, dép, hàng da và giả da');
INSERT INTO "industry_codes" VALUES ('9524','Sửa chữa giường, tủ, bàn, ghế và đồ nội thất tương tự');
INSERT INTO "industry_codes" VALUES ('9529','Sửa chữa xe đạp, đồng hồ, đồ dùng cá nhân và gia đình khác chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('9610','Dịch vụ tắm hơi, massage và các dịch vụ tăng cường sức khoẻ tương tự (trừ hoạt động thể thao)');
INSERT INTO "industry_codes" VALUES ('9620','Giặt là, làm sạch các sản phẩm dệt và lông thú');
INSERT INTO "industry_codes" VALUES ('9631','Cắt tóc, làm đầu, gội đầu');
INSERT INTO "industry_codes" VALUES ('9632','Hoạt động dịch vụ phục vụ tang lễ');
INSERT INTO "industry_codes" VALUES ('9633','Hoạt động dịch vụ phục vụ hôn lễ');
INSERT INTO "industry_codes" VALUES ('9639','Hoạt động dịch vụ phục vụ cá nhân khác còn lại chưa được phân vào đâu');
INSERT INTO "industry_codes" VALUES ('9700','Hoạt động làm thuê công việc gia đình trong các hộ gia đình');
INSERT INTO "industry_codes" VALUES ('9810','Hoạt động sản xuất các sản phẩm vật chất tự tiêu dùng của hộ gia đình');
INSERT INTO "industry_codes" VALUES ('9820','Hoạt động sản xuất các sản phẩm dịch vụ tự tiêu dùng của hộ gia đình');
INSERT INTO "industry_codes" VALUES ('9900','Hoạt động của các tổ chức và cơ quan quốc tế');
COMMIT;
